[workspace]
members = [
    "day1",
    "day2",
    "day3",
    "day4",
    "day5", 
    "day6", 
    "day7"
]
resolver = "2"

[workspace.dependencies]
futures = "0.3.31"
futures-concurrency = "7.6.2"
tokio = { version = "1.42", features = ['full'] }
